name: SplashKit Core Windows
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include: [
          { msystem: MINGW64, arch: x86_64, path: win64 },
          # { msystem: MINGW32, arch: i686,   path: win32 }
        ]
    defaults:
      run:
        shell: msys2 {0}
        working-directory: projects/cmake
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          path-type: inherit
          update: true
          install: git make wget tar patch dos2unix diffutils ca-certificates mingw-w64-${{ matrix.arch }}-make mingw-w64-${{ matrix.arch }}-cmake mingw-w64-${{ matrix.arch }}-ca-certificates mingw-w64-${{ matrix.arch }}-gcc mingw-w64-${{ matrix.arch }}-libpng cmake mingw-w64-${{ matrix.arch }}-SDL2 mingw-w64-${{ matrix.arch }}-SDL2_gfx mingw-w64-${{ matrix.arch }}-SDL2_image mingw-w64-${{ matrix.arch }}-SDL2_mixer mingw-w64-${{ matrix.arch }}-SDL2_net mingw-w64-${{ matrix.arch }}-SDL2_sound mingw-w64-${{ matrix.arch }}-SDL2_ttf
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: build
        working-directory: ./projects/cmake
        run: |
          cmake -G "Unix Makefiles" .
          make -j 2
      - name: execute
        working-directory: ./bin
        run: |
          export PATH=../coresdk/lib/${{ matrix.path }}:$PATH
          echo $PATH
          ./skunit_tests
